<?php

namespace AppBundle\Repository;

/**
 * BrouillonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrouillonRepository extends \Doctrine\ORM\EntityRepository
{
}
